---
user: ubuntu
group: ubuntu
sudoers: ubuntu

repoDocker: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - python3-apt
  - software-properties-common

swapfile:
  - swap
  - none
