---
- name: Copy join command remote to local file
  copy:
    src: join-command
    dest: join-command.sh
    mode: 0777

#- name: Copy the join command to server location
#  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Join the node to cluster
  command: sh join-command.sh
